# Copyright (c) 2023-2023 Huawei Device Co., Ltd. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//kernel/liteos_m/liteos.gni")

module_name = get_path_info(rebase_path("."), "name")
kernel_module(module_name) {
  sources = [ 
    "main.c",
    "systick.c",
    "gd32f4xx_it.c",
    "//device/board/GigaDevice/components/startup/startup_gd32f450_470.S",
    "${ohos_root_path}device/soc/gd32f4/CMSIS/GD/GD32F4XX/Source/system_gd32f4xx.c",
  ]
}

config("public") {
    ldflags = [
        "-Wl,--wrap=_calloc_r",
        "-Wl,--wrap=_malloc_r",
        "-Wl,--wrap=_realloc_r",
        "-Wl,--wrap=_reallocf_r",
        "-Wl,--wrap=_free_r",
        "-Wl,--wrap=_memalign_r",
        "-Wl,--wrap=_malloc_usable_size_r",
        "-Wl,--wrap=_calloc_r",
    ]
    
    lib_dirs = [ "$root_out_dir/libs" ]
    ldflags += [
        "-Wl,--whole-archive",
        "-lbootstrap",                            # 
        "-lbroadcast",                            #
        "-lsamgr",
        "-Wl,--no-whole-archive",
    ]

    libs = [
        "c",
        "m",
        "nosys",
    ]
}